# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  hardware.cpu.amd.updateMicrocode = true;

  fileSystems."/" =
    {
      device = "/dev/disk/by-label/NIXROOT";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-label/NIXBOOT";
      fsType = "vfat";
    };

  swapDevices = [
    {
      device = "/.swapfile";
    }
  ];

  # high-resolution display (was autodetected but wrong, have good eyesight and like more screen real estate)
  hardware.video.hidpi.enable = false;

  systemd.network.links."10-en-usb-0" = {
    matchConfig.PermanentMACAddress = "8c:ae:4c:dd:20:d8";
    linkConfig.Name = "en-usb-0";
  };
}
