# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ lib, ... }:

{
  fileSystems."/persist" =
    {
      device = "/dev/disk/by-label/amayadori_persist";
      fsType = "btrfs";
      neededForBoot = true;
      options = [ "defaults" "subvol=@persist" "ssd" "discard=async" "rw" "noatime" "compress=zstd" "space_cache=v2" "autodefrag" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-partuuid/10b3a7b6-a427-4597-bfc1-c6b18bc1208f";
      fsType = "vfat";
      neededForBoot = true;
    };
  fileSystems."/" = {
    device = "tmpfs";
    fsType = "tmpfs";
    options = [ "defaults" "size=2G" "mode=755" ];
    neededForBoot = true;
  };

  swapDevices = lib.mkForce [
    {
      device = "/dev/disk/by-partlabel/_swap";
    }
  ];
}
