[theme]
theme = "solarized-dark"
[icons]
icons = "awesome6"

[[block]]
block = "disk_space"
path = "/persist"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"

[[block]]
block = "cpu"
interval = 1

# [[block]]
# block = "load"
# interval = 1
# format = "{1m}"

[[block]]
block = "net"
interval = 5
format = " $icon $signal_strength$frequency "

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 10
format = " $icon $timestamp.datetime(f:'%F %R') "

[[block]]
block = "custom"
command = "cat /etc/hostname"
interval = "once"

[[block]]
block = "backlight"

[[block]]
block = "temperature"
format = " $icon $max max "
format_alt = " $icon $min min, $max max, $average avg "
interval = 10
chip = "*-virtual-0"

[[block]]
block = "battery"

[[block]]
block = "custom"
command = "echo \uf011" # assumes fontawesome icons
interval = "once"
[[block.click]]
button = "left"
cmd = "systemctl `echo -e 'suspend\npoweroff\nreboot' | dmenu`"
