theme = "gruvbox-dark"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/persist"
# alias = "persist"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mug}GB ({Mup}%)"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "net"
ssid = true
ip = true
speed_up = false
graph_up = true
interval = 5

[[block]]
block = "sound"
on_click = "pulsemixer --toggle-mute"

[[block]]
block = "time"
interval = 60
format = "%a %m/%d %I:%M"

[[block]]
block = "battery"
