# https://nixos.org/guides/continuous-integration-github-actions.html
name: "Test"
permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Cache multiple paths
      uses: actions/cache@v2
      with:
        path: |
          /nix/store
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v16
      with:
        install_url: https://releases.nixos.org/nix/nix-2.4/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - uses: cachix/cachix-action@v10
      with:
        name: nix-community
    - run: nix-channel --add https://nixos.org/channels/nixos-21.11
    - run: nix-channel --update
    - run: nix-shell -p nixos-rebuild --run true
    - run: nix flake metadata
    - run: nix flake show
    - run: nix flake check
    - run: >
       nix-shell -p nixos-rebuild --run 'nix flake show --json | jq '\''.nixosConfigurations | keys[] as $k | select(.[$k].type=="nixos-configuration") | $k'\'' -cr | xargs -tI{} nixos-rebuild build --flake .#{}'
    - run: >
       nix flake show --json | jq 'del(.devShell) | [leaf_paths as $path | select(getpath($path) == "derivation") | {"key": $path | join(".") | sub(".type";""), "value": getpath($path)}] | from_entries | keys|.[]' -cr | xargs -tI{} nix build .#{}
    - run: echo Done
